export const CURRENCY_LIST_REQUEST = 'common/CURRENCY_LIST_REQUEST';
export const CURRENCY_LIST_RECEIVED = 'common/CURRENCY_LIST_RECEIVED';
export const CURRENCY_LIST_ERROR = 'common/CURRENCY_LIST_ERROR';
